//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TripNPick.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class hostel
    {
        public int hostel_id { get; set; }
        public string hostel_id_gg { get; set; }
        public string hostel_name { get; set; }
        public Nullable<double> hostel_lat { get; set; }
        public Nullable<double> hostel_long { get; set; }
        public string hostel_address { get; set; }
        public Nullable<double> hostel_rating { get; set; }
        public Nullable<int> suburb_id { get; set; }
    
        public virtual suburb_table suburb_table { get; set; }
    }
}
