//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TripNPick.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class interest_attraction
    {
        public int attraction_id { get; set; }
        public Nullable<int> suburb_id { get; set; }
        public string interest_place_name { get; set; }
        public Nullable<double> review_grade { get; set; }
        public Nullable<double> number_of_reviews { get; set; }
        public string tag { get; set; }
        public string address_x { get; set; }
        public string phone { get; set; }
        public string review_highlights { get; set; }
        public string review_keyword { get; set; }
        public string types { get; set; }
        public string attraction_name { get; set; }
        public Nullable<double> location_lat { get; set; }
        public Nullable<double> location_lng { get; set; }
        public int interest_id { get; set; }
    
        public virtual interest_table interest_table { get; set; }
        public virtual suburb_table suburb_table { get; set; }
    }
}
