//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TripNPick.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class suburb_table
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public suburb_table()
        {
            this.farms = new HashSet<farm>();
            this.suburb_harvest = new HashSet<suburb_harvest>();
            this.interest_attraction = new HashSet<interest_attraction>();
        }
    
        public int suburb_id { get; set; }
        public string suburb_name { get; set; }
        public string state { get; set; }
        public Nullable<int> station_id { get; set; }
        public Nullable<double> suburb_lat { get; set; }
        public Nullable<double> suburb_lng { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<farm> farms { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<suburb_harvest> suburb_harvest { get; set; }
        public virtual weather_cold_days weather_cold_days { get; set; }
        public virtual weather_hot_days weather_hot_days { get; set; }
        public virtual weather_rainy_days weather_rainy_days { get; set; }
        public virtual weather_temp3pm_days weather_temp3pm_days { get; set; }
        public virtual weather_temp9am_days weather_temp9am_days { get; set; }
        public virtual state state1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<interest_attraction> interest_attraction { get; set; }
    }
}
