//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TripNPick.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class suburb_harvest
    {
        public int suburb_harvest_id { get; set; }
        public int suburb_id { get; set; }
        public int crop_id { get; set; }
        public string january { get; set; }
        public string february { get; set; }
        public string march { get; set; }
        public string april { get; set; }
        public string may { get; set; }
        public string june { get; set; }
        public string july { get; set; }
        public string august { get; set; }
        public string september { get; set; }
        public string october { get; set; }
        public string november { get; set; }
        public string december { get; set; }
    
        public virtual crop crop { get; set; }
        public virtual suburb_table suburb_table { get; set; }
    }
}
