//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TripNPick.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ColdSpotDBEntities : DbContext
    {
        public ColdSpotDBEntities()
            : base("name=ColdSpotDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<crop> crops { get; set; }
        public virtual DbSet<fake_farms> fake_farms { get; set; }
        public virtual DbSet<farm> farms { get; set; }
        public virtual DbSet<hostel> hostels { get; set; }
        public virtual DbSet<interest_attraction> interest_attraction { get; set; }
        public virtual DbSet<interest_table> interest_table { get; set; }
        public virtual DbSet<Registration> Registrations { get; set; }
        public virtual DbSet<state> states { get; set; }
        public virtual DbSet<suburb_harvest> suburb_harvest { get; set; }
        public virtual DbSet<suburb_table> suburb_table { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<weather_cold_days> weather_cold_days { get; set; }
        public virtual DbSet<weather_hot_days> weather_hot_days { get; set; }
        public virtual DbSet<weather_rainy_days> weather_rainy_days { get; set; }
        public virtual DbSet<weather_temp3pm_days> weather_temp3pm_days { get; set; }
        public virtual DbSet<weather_temp9am_days> weather_temp9am_days { get; set; }
    }
}
