//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TripNPick.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class weather_hot_days
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public weather_hot_days()
        {
            this.suburb_table = new HashSet<suburb_table>();
        }
    
        public int station_id { get; set; }
        public string january { get; set; }
        public string february { get; set; }
        public string march { get; set; }
        public string april { get; set; }
        public string may { get; set; }
        public string june { get; set; }
        public string july { get; set; }
        public string august { get; set; }
        public string september { get; set; }
        public string october { get; set; }
        public string november { get; set; }
        public string december { get; set; }
        public string statistical_element { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<suburb_table> suburb_table { get; set; }
    }
}
